# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: wire_format.proto
# plugin: python-betterproto
# This file has been @generated
import warnings
from dataclasses import dataclass
from typing import (
    Dict,
    List,
)

import betterproto

from .....location.nearby.proto import sharing as ____location_nearby_proto_sharing__


class FileMetadataType(betterproto.Enum):
    UNKNOWN = 0
    IMAGE = 1
    VIDEO = 2
    ANDROID_APP = 3
    AUDIO = 4
    DOCUMENT = 5
    CONTACT_CARD = 6


class TextMetadataType(betterproto.Enum):
    UNKNOWN = 0
    TEXT = 1
    URL = 2
    """Open with browsers."""

    ADDRESS = 3
    """Open with map apps."""

    PHONE_NUMBER = 4
    """Dial."""


class WifiCredentialsMetadataSecurityType(betterproto.Enum):
    UNKNOWN_SECURITY_TYPE = 0
    OPEN = 1
    WPA_PSK = 2
    WEP = 3
    SAE = 4


class FrameVersion(betterproto.Enum):
    UNKNOWN_VERSION = 0
    V1 = 1


class V1FrameFrameType(betterproto.Enum):
    UNKNOWN_FRAME_TYPE = 0
    INTRODUCTION = 1
    RESPONSE = 2
    PAIRED_KEY_ENCRYPTION = 3
    PAIRED_KEY_RESULT = 4
    CERTIFICATE_INFO = 5
    """No longer used."""

    CANCEL = 6
    PROGRESS_UPDATE = 7
    """No longer used."""


class IntroductionFrameSharingUseCase(betterproto.Enum):
    UNKNOWN = 0
    NEARBY_SHARE = 1
    REMOTE_COPY = 2


class ConnectionResponseFrameStatus(betterproto.Enum):
    UNKNOWN = 0
    ACCEPT = 1
    REJECT = 2
    NOT_ENOUGH_SPACE = 3
    UNSUPPORTED_ATTACHMENT_TYPE = 4
    TIMED_OUT = 5


class AttachmentDetailsType(betterproto.Enum):
    """LINT.IfChange"""

    UNKNOWN = 0
    FILE = 1
    """Represents FileAttachment."""

    TEXT = 2
    """Represents TextAttachment."""

    WIFI_CREDENTIALS = 3
    """Represents WifiCredentialsAttachment."""

    APP = 4
    """Represents AppAttachment."""

    STREAM = 5
    """Represents StreamAttachment."""


class PairedKeyResultFrameStatus(betterproto.Enum):
    UNKNOWN = 0
    SUCCESS = 1
    FAIL = 2
    UNABLE = 3


@dataclass(eq=False, repr=False)
class FileMetadata(betterproto.Message):
    """
    File metadata. Does not include the actual bytes of the file.
     NEXT_ID=10
    """

    name: str = betterproto.string_field(1)
    """The human readable name of this file (eg. 'Cookbook.pdf')."""

    type: "FileMetadataType" = betterproto.enum_field(2)
    """
    The type of file (eg. 'IMAGE' from 'dog.jpg'). Specifying a type helps
     provide a richer experience on the receiving side.
    """

    payload_id: int = betterproto.int64_field(3)
    """
    The FILE payload id that will be sent as a follow up containing the actual
     bytes of the file.
    """

    size: int = betterproto.int64_field(4)
    """The total size of the file."""

    mime_type: str = betterproto.string_field(5)
    """
    The mimeType of file (eg. 'image/jpeg' from 'dog.jpg'). Specifying a
     mimeType helps provide a richer experience on receiving side.
    """

    id: int = betterproto.int64_field(6)
    """A uuid for the attachment. Should be unique across all attachments."""

    parent_folder: str = betterproto.string_field(7)
    """The parent folder."""

    attachment_hash: int = betterproto.int64_field(8)
    """
    A stable identifier for the attachment. Used for receiver to identify same
     attachment from different transfers.
    """

    is_sensitive_content: bool = betterproto.bool_field(9)
    """True, if image in file attachment is sensitive"""


@dataclass(eq=False, repr=False)
class TextMetadata(betterproto.Message):
    """NEXT_ID=8"""

    text_title: str = betterproto.string_field(2)
    """The title of the text content."""

    type: "TextMetadataType" = betterproto.enum_field(3)
    """The type of text (phone number, url, address, or plain text)."""

    payload_id: int = betterproto.int64_field(4)
    """
    The BYTE payload id that will be sent as a follow up containing the actual
     bytes of the text.
    """

    size: int = betterproto.int64_field(5)
    """The size of the text content."""

    id: int = betterproto.int64_field(6)
    """A uuid for the attachment. Should be unique across all attachments."""

    is_sensitive_text: bool = betterproto.bool_field(7)
    """True if text is sensitive, e.g. password"""


@dataclass(eq=False, repr=False)
class WifiCredentialsMetadata(betterproto.Message):
    """NEXT_ID=6"""

    ssid: str = betterproto.string_field(2)
    """The Wifi network name. This will be sent in introduction."""

    security_type: "WifiCredentialsMetadataSecurityType" = betterproto.enum_field(3)
    """The security type of network (OPEN, WPA_PSK, WEP)."""

    payload_id: int = betterproto.int64_field(4)
    """
    The BYTE payload id that will be sent as a follow up containing the
     password.
    """

    id: int = betterproto.int64_field(5)
    """A uuid for the attachment. Should be unique across all attachments."""


@dataclass(eq=False, repr=False)
class AppMetadata(betterproto.Message):
    """NEXT_ID=8"""

    app_name: str = betterproto.string_field(1)
    """The app name. This will be sent in introduction."""

    size: int = betterproto.int64_field(2)
    """The size of the all split of apks."""

    payload_id: List[int] = betterproto.int64_field(3)
    """
    The File payload id that will be sent as a follow up containing the
     apk paths.
    """

    id: int = betterproto.int64_field(4)
    """A uuid for the attachment. Should be unique across all attachments."""

    file_name: List[str] = betterproto.string_field(5)
    """The name of apk file. This will be sent in introduction."""

    file_size: List[int] = betterproto.int64_field(6)
    """The size of apk file. This will be sent in introduction."""

    package_name: str = betterproto.string_field(7)
    """The package name. This will be sent in introduction."""


@dataclass(eq=False, repr=False)
class StreamMetadata(betterproto.Message):
    """NEXT_ID=5"""

    description: str = betterproto.string_field(1)
    """A human readable description for the stream."""

    package_name: str = betterproto.string_field(2)
    """The package name of the sending application."""

    payload_id: int = betterproto.int64_field(3)
    """
    The <TYPE> payload id that will be send as a followup containing the
     ParcelFileDescriptor.
    """

    attributed_app_name: str = betterproto.string_field(4)
    """
    The human-readable name of the package that should be displayed as
     attribution if no other information is available (i.e. the package is not
     installed locally yet).
    """


@dataclass(eq=False, repr=False)
class Frame(betterproto.Message):
    """
    A frame used when sending messages over the wire.
     NEXT_ID=3
    """

    version: "FrameVersion" = betterproto.enum_field(1)
    v1: "V1Frame" = betterproto.message_field(2)
    """
    Right now there's only 1 version, but if there are more, exactly one of
     the following fields will be set.
    """


@dataclass(eq=False, repr=False)
class V1Frame(betterproto.Message):
    """NEXT_ID=8"""

    type: "V1FrameFrameType" = betterproto.enum_field(1)
    introduction: "IntroductionFrame" = betterproto.message_field(2)
    """At most one of the following fields will be set."""

    connection_response: "ConnectionResponseFrame" = betterproto.message_field(3)
    paired_key_encryption: "PairedKeyEncryptionFrame" = betterproto.message_field(4)
    paired_key_result: "PairedKeyResultFrame" = betterproto.message_field(5)
    certificate_info: "CertificateInfoFrame" = betterproto.message_field(6)
    progress_update: "ProgressUpdateFrame" = betterproto.message_field(7)

    def __post_init__(self) -> None:
        super().__post_init__()
        if self.is_set("certificate_info"):
            warnings.warn("V1Frame.certificate_info is deprecated", DeprecationWarning)
        if self.is_set("progress_update"):
            warnings.warn("V1Frame.progress_update is deprecated", DeprecationWarning)


@dataclass(eq=False, repr=False)
class IntroductionFrame(betterproto.Message):
    """
    An introduction packet sent by the sending side. Contains a list of files
     they'd like to share.
     NEXT_ID=10
    """

    file_metadata: List["FileMetadata"] = betterproto.message_field(1)
    text_metadata: List["TextMetadata"] = betterproto.message_field(2)
    required_package: str = betterproto.string_field(3)
    """The required app package to open the content. May be null."""

    wifi_credentials_metadata: List["WifiCredentialsMetadata"] = (
        betterproto.message_field(4)
    )
    app_metadata: List["AppMetadata"] = betterproto.message_field(5)
    start_transfer: bool = betterproto.bool_field(6)
    stream_metadata: List["StreamMetadata"] = betterproto.message_field(7)
    use_case: "IntroductionFrameSharingUseCase" = betterproto.enum_field(8)
    preview_payload_ids: List[int] = betterproto.int64_field(9)


@dataclass(eq=False, repr=False)
class ProgressUpdateFrame(betterproto.Message):
    """
    A progress update packet sent by the sending side. Contains transfer progress
     value. NEXT_ID=3
    """

    progress: float = betterproto.float_field(1)
    start_transfer: bool = betterproto.bool_field(2)
    """
    True, if the receiver should start bandwidth upgrade and receiving the
     payloads.
    """


@dataclass(eq=False, repr=False)
class ConnectionResponseFrame(betterproto.Message):
    """
    A response packet sent by the receiving side. Accepts or rejects the list of
     files.
     NEXT_ID=4
    """

    status: "ConnectionResponseFrameStatus" = betterproto.enum_field(1)
    """The receiving side's response."""

    attachment_details: Dict[int, "AttachmentDetails"] = betterproto.map_field(
        2, betterproto.TYPE_INT64, betterproto.TYPE_MESSAGE
    )
    """Key is attachment hash, value is the details of attachment."""

    stream_metadata: List["StreamMetadata"] = betterproto.message_field(3)
    """
    In the case of a stream attachments, the other side of the pipe.
     Both sender and receiver should validate matching counts.
    """


@dataclass(eq=False, repr=False)
class AttachmentDetails(betterproto.Message):
    """
    Attachment details that sent in ConnectionResponseFrame.
     NEXT_ID=3
    """

    type: "AttachmentDetailsType" = betterproto.enum_field(1)
    """The attachment family type."""

    file_attachment_details: "FileAttachmentDetails" = betterproto.message_field(2)
    """This field is only for FILE type."""


@dataclass(eq=False, repr=False)
class FileAttachmentDetails(betterproto.Message):
    """
    File attachment details included in ConnectionResponseFrame.
     NEXT_ID=3
    """

    receiver_existing_file_size: int = betterproto.int64_field(1)
    """Existing local file size on receiver side."""

    attachment_hash_payloads: Dict[int, "PayloadsDetails"] = betterproto.map_field(
        2, betterproto.TYPE_INT64, betterproto.TYPE_MESSAGE
    )
    """
    The key is attachment hash, a stable identifier for the attachment.
     Value is list of payload details transferred for the attachment.
    """


@dataclass(eq=False, repr=False)
class PayloadsDetails(betterproto.Message):
    """NEXT_ID=2"""

    payload_details: List["PayloadDetails"] = betterproto.message_field(1)
    """The list should be sorted by creation timestamp."""


@dataclass(eq=False, repr=False)
class PayloadDetails(betterproto.Message):
    """
    Metadata of a payload file created by Nearby Connections.
     NEXT_ID=4
    """

    id: int = betterproto.int64_field(1)
    creation_timestamp_millis: int = betterproto.int64_field(2)
    size: int = betterproto.int64_field(3)


@dataclass(eq=False, repr=False)
class PairedKeyEncryptionFrame(betterproto.Message):
    """
    A paired key encryption packet sent between devices, contains signed data.
     NEXT_ID=5
    """

    signed_data: bytes = betterproto.bytes_field(1)
    """The encrypted data in byte array format."""

    secret_id_hash: bytes = betterproto.bytes_field(2)
    """The hash of a certificate id."""

    optional_signed_data: bytes = betterproto.bytes_field(3)
    """An optional encrypted data in byte array format."""

    qr_code_handshake_data: bytes = betterproto.bytes_field(4)
    """
    An optional QR code handshake data in a byte array format.
     For incoming connection contains a signature of the UKEY2
     token, created with the sender's private key.
     For outgoing connection contains an HKDF of the connection token and of the
     UKEY2 token
    """


@dataclass(eq=False, repr=False)
class PairedKeyResultFrame(betterproto.Message):
    """
    A paired key verification result packet sent between devices.
     NEXT_ID=3
    """

    status: "PairedKeyResultFrameStatus" = betterproto.enum_field(1)
    """The verification result."""

    os_type: "____location_nearby_proto_sharing__.OsType" = betterproto.enum_field(2)
    """OS type."""


@dataclass(eq=False, repr=False)
class CertificateInfoFrame(betterproto.Message):
    """
    A package containing certificate info to be shared to remote device offline.
     NEXT_ID=2
    """

    public_certificate: List["PublicCertificate"] = betterproto.message_field(1)
    """The public certificates to be shared with remote devices."""


@dataclass(eq=False, repr=False)
class PublicCertificate(betterproto.Message):
    """
    A public certificate from the local device.
     NEXT_ID=8
    """

    secret_id: bytes = betterproto.bytes_field(1)
    """The unique id of the public certificate."""

    authenticity_key: bytes = betterproto.bytes_field(2)
    """
    A bytes representation of a Secret Key owned by contact, to decrypt the
     metadata_key stored within the advertisement.
    """

    public_key: bytes = betterproto.bytes_field(3)
    """
    A bytes representation a public key of X509Certificate, owned by contact,
     to decrypt encrypted UKEY2 (from Nearby Connections API) as a hand shake in
     contact verification phase.
    """

    start_time: int = betterproto.int64_field(4)
    """
    The time in millis from epoch when this certificate becomes effective.
    """

    end_time: int = betterproto.int64_field(5)
    """The time in millis from epoch when this certificate expires."""

    encrypted_metadata_bytes: bytes = betterproto.bytes_field(6)
    """
    The encrypted metadata in bytes, contains personal information of the
     device/user who created this certificate. Needs to be decrypted into bytes,
     and converted back to EncryptedMetadata object to access fields.
    """

    metadata_encryption_key_tag: bytes = betterproto.bytes_field(7)
    """The tag for verifying metadata_encryption_key."""


@dataclass(eq=False, repr=False)
class WifiCredentials(betterproto.Message):
    """NEXT_ID=3"""

    password: str = betterproto.string_field(1)
    """Wi-Fi password."""

    hidden_ssid: bool = betterproto.bool_field(2)
    """
    True if the network is a hidden network that is not broadcasting its SSID.
     Default is false.
    """


@dataclass(eq=False, repr=False)
class StreamDetails(betterproto.Message):
    """NEXT_ID=2"""

    input_stream_parcel_file_descriptor_bytes: bytes = betterproto.bytes_field(1)
    """Serialized ParcelFileDescriptor for input stream (for the receiver)."""
