[project]
name = "pyquickshare"
version = "0.1.0"
description = ""
authors = [{ name = "teaishealthy", email = "teaishealthy@protonmail.com" }]
requires-python = "~=3.10"
readme = "README.md"
license = "MIT"
dependencies = [
    "bless>=0.2.6",
    "cryptography>=42.0.8",
    "dbus-next>=0.2.3",
    "protobuf>=5.26.1",
    "python-magic>=0.4.27",
    "zeroconf>=0.143.0",
]

[dependency-groups]
dev = ["ruff>=0.4.3,<0.5"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
