# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: securemessage.proto
# plugin: python-betterproto
# This file has been @generated

from dataclasses import dataclass

import betterproto


class SigScheme(betterproto.Enum):
    """
    Supported "signature" schemes (both symmetric key and public key based)
    """

    HMAC_SHA256 = 1
    ECDSA_P256_SHA256 = 2
    RSA2048_SHA256 = 3
    """Not recommended -- use ECDSA_P256_SHA256 instead"""


class EncScheme(betterproto.Enum):
    """Supported encryption schemes"""

    NONE = 1
    """No encryption"""

    AES_256_CBC = 2


class PublicKeyType(betterproto.Enum):
    """A list of supported public key types"""

    EC_P256 = 1
    RSA2048 = 2
    DH2048_MODP = 3
    """2048-bit MODP group 14, from RFC 3526"""


@dataclass(eq=False, repr=False)
class SecureMessage(betterproto.Message):
    header_and_body: bytes = betterproto.bytes_field(1)
    """Must contain a HeaderAndBody message"""

    signature: bytes = betterproto.bytes_field(2)
    """Signature of header_and_body"""


@dataclass(eq=False, repr=False)
class Header(betterproto.Message):
    signature_scheme: "SigScheme" = betterproto.enum_field(1)
    encryption_scheme: "EncScheme" = betterproto.enum_field(2)
    verification_key_id: bytes = betterproto.bytes_field(3)
    """Identifies the verification key"""

    decryption_key_id: bytes = betterproto.bytes_field(4)
    """Identifies the decryption key"""

    iv: bytes = betterproto.bytes_field(5)
    """Encryption may use an IV"""

    public_metadata: bytes = betterproto.bytes_field(6)
    """
    Arbitrary per-protocol public data, to be sent with the plain-text header
    """

    associated_data_length: int = betterproto.uint32_field(7)
    """
    The length of some associated data this is not sent in this SecureMessage,
     but which will be bound to the signature.
    """


@dataclass(eq=False, repr=False)
class HeaderAndBody(betterproto.Message):
    header: "Header" = betterproto.message_field(1)
    """Public data about this message (to be bound in the signature)"""

    body: bytes = betterproto.bytes_field(2)
    """Payload data"""


@dataclass(eq=False, repr=False)
class HeaderAndBodyInternal(betterproto.Message):
    """
    Must be kept wire-format compatible with HeaderAndBody. Provides the
     SecureMessage code with a consistent wire-format representation that
     remains stable irrespective of protobuf implementation choices. This
     low-level representation of a HeaderAndBody should not be used by
     any code outside of the SecureMessage library implementation/tests.
    """

    header: bytes = betterproto.bytes_field(1)
    """A raw (wire-format) byte encoding of a Header, suitable for hashing"""

    body: bytes = betterproto.bytes_field(2)
    """Payload data"""


@dataclass(eq=False, repr=False)
class EcP256PublicKey(betterproto.Message):
    """
    A convenience proto for encoding NIST P-256 elliptic curve public keys
    """

    x: bytes = betterproto.bytes_field(1)
    """
    x and y are encoded in big-endian two's complement (slightly wasteful)
     Client MUST verify (x,y) is a valid point on NIST P256
    """

    y: bytes = betterproto.bytes_field(2)


@dataclass(eq=False, repr=False)
class SimpleRsaPublicKey(betterproto.Message):
    """
    A convenience proto for encoding RSA public keys with small exponents
    """

    n: bytes = betterproto.bytes_field(1)
    """Encoded in big-endian two's complement"""

    e: int = betterproto.int32_field(2)


@dataclass(eq=False, repr=False)
class DhPublicKey(betterproto.Message):
    """
    A convenience proto for encoding Diffie-Hellman public keys,
     for use only when Elliptic Curve based key exchanges are not possible.
     (Note that the group parameters must be specified separately)
    """

    y: bytes = betterproto.bytes_field(1)
    """Big-endian two's complement encoded group element"""


@dataclass(eq=False, repr=False)
class GenericPublicKey(betterproto.Message):
    type: "PublicKeyType" = betterproto.enum_field(1)
    ec_p256_public_key: "EcP256PublicKey" = betterproto.message_field(2)
    rsa2048_public_key: "SimpleRsaPublicKey" = betterproto.message_field(3)
    dh2048_public_key: "DhPublicKey" = betterproto.message_field(4)
    """Use only as a last resort"""
