# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: device_to_device_messages.proto, securegcm.proto, ukey.proto
# plugin: python-betterproto
# This file has been @generated

from dataclasses import dataclass
from typing import List

import betterproto

from .. import securemessage as _securemessage__


class Curve(betterproto.Enum):
    """Type of curve"""

    ED_25519 = 1


class AppleDeviceDiagonalMils(betterproto.Enum):
    """
    This enum is used by iOS devices as values for device_display_diagonal_mils
     in GcmDeviceInfo. There is no good way to calculate it on those devices.
    """

    APPLE_PHONE = 4000
    """This is the mils diagonal on an iPhone 5."""

    APPLE_PAD = 7900
    """This is the mils diagonal on an iPad mini."""


class DeviceType(betterproto.Enum):
    """
    This should be kept in sync with DeviceType in:
     java/com/google/security/cryptauth/backend/services/common/common_enums.proto
    """

    UNKNOWN = 0
    ANDROID = 1
    CHROME = 2
    IOS = 3
    BROWSER = 4
    OSX = 5


class SoftwareFeature(betterproto.Enum):
    """
    MultiDevice features which may be supported and enabled on a device. See
    """

    UNKNOWN_FEATURE = 0
    BETTER_TOGETHER_HOST = 1
    BETTER_TOGETHER_CLIENT = 2
    EASY_UNLOCK_HOST = 3
    EASY_UNLOCK_CLIENT = 4
    MAGIC_TETHER_HOST = 5
    MAGIC_TETHER_CLIENT = 6
    SMS_CONNECT_HOST = 7
    SMS_CONNECT_CLIENT = 8


class InvocationReason(betterproto.Enum):
    """
    A list of "reasons" that can be provided for calling server-side APIs.
     This is particularly important for calls that can be triggered by different
     kinds of events. Please try to keep reasons as generic as possible, so that
     codes can be re-used by various callers in a sensible fashion.
    """

    REASON_UNKNOWN = 0
    REASON_INITIALIZATION = 1
    """First run of the software package invoking this call"""

    REASON_PERIODIC = 2
    """Ordinary periodic actions (e.g. monthly master key rotation)"""

    REASON_SLOW_PERIODIC = 3
    """Slow-cycle periodic action (e.g. yearly keypair rotation???)"""

    REASON_FAST_PERIODIC = 4
    """Fast-cycle periodic action (e.g. daily sync for Smart Lock users)"""

    REASON_EXPIRATION = 5
    """
    Expired state (e.g. expired credentials, or cached entries) was detected
    """

    REASON_FAILURE_RECOVERY = 6
    """
    An unexpected protocol failure occurred (so attempting to repair state)
    """

    REASON_NEW_ACCOUNT = 7
    """A new account has been added to the device"""

    REASON_CHANGED_ACCOUNT = 8
    """An existing account on the device has been changed"""

    REASON_FEATURE_TOGGLED = 9
    """
    The user toggled the state of a feature (e.g. Smart Lock enabled via BT)
    """

    REASON_SERVER_INITIATED = 10
    """A "push" from the server caused this action (e.g. a sync tickle)"""

    REASON_ADDRESS_CHANGE = 11
    """
    A local address change triggered this (e.g. GCM registration id changed)
    """

    REASON_SOFTWARE_UPDATE = 12
    """A software update has triggered this"""

    REASON_MANUAL = 13
    """
    A manual action by the user triggered this (e.g. commands sent via adb)
    """

    REASON_CUSTOM_KEY_INVALIDATION = 14
    """
    A custom key has been invalidated on the device (e.g. screen lock is
     disabled).
    """

    REASON_PROXIMITY_PERIODIC = 15
    """Periodic action triggered by auth_proximity"""


class Type(betterproto.Enum):
    ENROLLMENT = 0
    TICKLE = 1
    TX_REQUEST = 2
    TX_REPLY = 3
    TX_SYNC_REQUEST = 4
    TX_SYNC_RESPONSE = 5
    TX_PING = 6
    DEVICE_INFO_UPDATE = 7
    TX_CANCEL_REQUEST = 8
    PROXIMITYAUTH_PAIRING = 10
    """DEPRECATED (can be re-used after Aug 2015)"""

    GCMV1_IDENTITY_ASSERTION = 11
    """
    The kind of identity assertion generated by a "GCM V1" device (i.e.,
     an Android phone that has registered with us a public and a symmetric
     key)
    """

    DEVICE_TO_DEVICE_RESPONDER_HELLO_PAYLOAD = 12
    """
    Device-to-device communications are protected by an unauthenticated
     Diffie-Hellman exchange. The InitiatorHello message is simply the
     initiator's public DH key, and is not encoded as a SecureMessage, so
     it doesn't have a tag.
     The ResponderHello message (which is sent by the responder
     to the initiator), on the other hand, carries a payload that is protected
     by the derived shared key. It also contains the responder's
     public DH key. ResponderHelloAndPayload messages have the
     DEVICE_TO_DEVICE_RESPONDER_HELLO tag.
    """

    DEVICE_TO_DEVICE_MESSAGE = 13
    """
    Device-to-device communications are protected by an unauthenticated
     Diffie-Hellman exchange. Once the initiator and responder
     agree on a shared key (through Diffie-Hellman), they will use messages
     tagged with DEVICE_TO_DEVICE_MESSAGE to exchange data.
    """

    DEVICE_PROXIMITY_CALLBACK = 14
    """Notification to let a device know it should contact a nearby device."""

    UNLOCK_KEY_SIGNED_CHALLENGE = 15
    """
    Device-to-device communications are protected by an unauthenticated
     Diffie-Hellman exchange. During device-to-device authentication, the first
     message from initiator (the challenge) is signed and put into the payload
     of the message sent back to the initiator.
    """

    LOGIN_NOTIFICATION = 101
    """Specialty (corp only) features"""


class Ukey2HandshakeCipher(betterproto.Enum):
    RESERVED = 0
    P256_SHA512 = 100
    CURVE25519_SHA512 = 200
    """commitment"""


class Ukey2MessageType(betterproto.Enum):
    UNKNOWN_DO_NOT_USE = 0
    ALERT = 1
    CLIENT_INIT = 2
    SERVER_INIT = 3
    CLIENT_FINISH = 4


class Ukey2AlertAlertType(betterproto.Enum):
    BAD_MESSAGE = 1
    """Framing errors"""

    BAD_MESSAGE_TYPE = 2
    INCORRECT_MESSAGE = 3
    BAD_MESSAGE_DATA = 4
    """expected type at this stage of the protocol"""

    BAD_VERSION = 100
    """ClientInit and ServerInit errors"""

    BAD_RANDOM = 101
    """suitable version to speak with client."""

    BAD_HANDSHAKE_CIPHER = 102
    """length"""

    BAD_NEXT_PROTOCOL = 103
    BAD_PUBLIC_KEY = 104
    """unsupported"""

    INTERNAL_ERROR = 200
    """Other errors"""


@dataclass(eq=False, repr=False)
class DeviceToDeviceMessage(betterproto.Message):
    """Used by protocols between devices"""

    message: bytes = betterproto.bytes_field(1)
    """the payload of the message"""

    sequence_number: int = betterproto.int32_field(2)
    """the sequence number of the message - must be increasing."""


@dataclass(eq=False, repr=False)
class InitiatorHello(betterproto.Message):
    """
    sent as the first message from initiator to responder
     in an unauthenticated Diffie-Hellman Key Exchange
    """

    public_dh_key: "_securemessage__.GenericPublicKey" = betterproto.message_field(1)
    """The session public key to send to the responder"""

    protocol_version: int = betterproto.int32_field(2)
    """The protocol version"""


@dataclass(eq=False, repr=False)
class ResponderHello(betterproto.Message):
    """
    sent inside the header of the first message from the responder to the
     initiator in an unauthenticated Diffie-Hellman Key Exchange
    """

    public_dh_key: "_securemessage__.GenericPublicKey" = betterproto.message_field(1)
    """The session public key to send to the initiator"""

    protocol_version: int = betterproto.int32_field(2)
    """The protocol version"""


@dataclass(eq=False, repr=False)
class EcPoint(betterproto.Message):
    """
    A convenience proto for encoding curve points in affine representation
    """

    curve: "Curve" = betterproto.enum_field(1)
    x: bytes = betterproto.bytes_field(2)
    """
    x and y are encoded in big-endian two's complement
     client MUST verify (x,y) is a valid point on the specified curve
    """

    y: bytes = betterproto.bytes_field(3)


@dataclass(eq=False, repr=False)
class SpakeHandshakeMessage(betterproto.Message):
    flow_number: int = betterproto.int32_field(1)
    """Each flow in the protocol bumps this counter"""

    ec_point: "EcPoint" = betterproto.message_field(2)
    """Some (but not all) SPAKE flows send a point on an elliptic curve"""

    hash_value: bytes = betterproto.bytes_field(3)
    """Some (but not all) SPAKE flows send a hash value"""

    payload: bytes = betterproto.bytes_field(4)
    """
    The last flow of a SPAKE protocol can send an optional payload,
     since the key exchange is already complete on the sender's side.
    """


@dataclass(eq=False, repr=False)
class GcmDeviceInfo(betterproto.Message):
    """
    Message used only during enrollment
     Field numbers should be kept in sync with DeviceInfo in:
       java/com/google/security/cryptauth/backend/services/common/common.proto
    """

    android_device_id: int = betterproto.fixed64_field(1)
    """
    This field's name does not match the one in DeviceInfo for legacy reasons.
     Consider using long_device_id and device_type instead when enrolling
     non-android devices.
    """

    gcm_registration_id: bytes = betterproto.bytes_field(102)
    """
    Used for device_address of DeviceInfo field 2, but for GCM capable devices.
    """

    apn_registration_id: bytes = betterproto.bytes_field(202)
    """Used for device_address of DeviceInfo field 2, but for iOS devices."""

    notification_enabled: bool = betterproto.bool_field(203)
    """
    Does the user have notifications enabled for the given device address.
    """

    bluetooth_mac_address: str = betterproto.string_field(302)
    """
    Used for device_address of DeviceInfo field 2, a Bluetooth Mac address for
     the device (e.g., to be used with EasyUnlock)
    """

    device_master_key_hash: bytes = betterproto.bytes_field(103)
    """
    SHA-256 hash of the device master key (from the key exchange).
     Differs from DeviceInfo field 3, which contains the actual master key.
    """

    user_public_key: bytes = betterproto.bytes_field(4)
    """A SecureMessage.EcP256PublicKey"""

    device_model: str = betterproto.string_field(7)
    """
    device's model name
     (e.g., an android.os.Build.MODEL or UIDevice.model)
    """

    locale: str = betterproto.string_field(8)
    """device's locale"""

    key_handle: bytes = betterproto.bytes_field(9)
    """The handle for user_public_key (and implicitly, a master key)"""

    counter: int = betterproto.int64_field(12)
    """The initial counter value for the device, sent by the device"""

    device_os_version: str = betterproto.string_field(13)
    """
    The Operating System version on the device
     (e.g., an android.os.Build.DISPLAY or UIDevice.systemVersion)
    """

    device_os_version_code: int = betterproto.int64_field(14)
    """
    The Operating System version number on the device
     (e.g., an android.os.Build.VERSION.SDK_INT)
    """

    device_os_release: str = betterproto.string_field(15)
    """
    The Operating System release on the device
     (e.g., an android.os.Build.VERSION.RELEASE)
    """

    device_os_codename: str = betterproto.string_field(16)
    """
    The Operating System codename on the device
     (e.g., an android.os.Build.VERSION.CODENAME or UIDevice.systemName)
    """

    device_software_version: str = betterproto.string_field(17)
    """
    The software version running on the device
     (e.g., Authenticator app version string)
    """

    device_software_version_code: int = betterproto.int64_field(18)
    """
    The software version number running on the device
     (e.g., Authenticator app version code)
    """

    device_software_package: str = betterproto.string_field(19)
    """
    Software package information if applicable
     (e.g., com.google.android.apps.authenticator2)
    """

    device_display_diagonal_mils: int = betterproto.int32_field(22)
    """
    Size of the display in thousandths of an inch (e.g., 7000 mils = 7 in)
    """

    device_authzen_version: int = betterproto.int32_field(24)
    """For Authzen capable devices, their Authzen protocol version"""

    long_device_id: bytes = betterproto.bytes_field(29)
    """Not all devices have device identifiers that fit in 64 bits."""

    device_manufacturer: str = betterproto.string_field(31)
    """
    The device manufacturer name
     (e.g., android.os.Build.MANUFACTURER)
    """

    device_type: "DeviceType" = betterproto.enum_field(32)
    """Used to indicate which type of device this is."""

    using_secure_screenlock: bool = betterproto.bool_field(400)
    """
    Is this device using  a secure screenlock (e.g., pattern or pin unlock)
    """

    auto_unlock_screenlock_supported: bool = betterproto.bool_field(401)
    """Is auto-unlocking the screenlock (e.g., when at "home") supported?"""

    auto_unlock_screenlock_enabled: bool = betterproto.bool_field(402)
    """Is auto-unlocking the screenlock (e.g., when at "home") enabled?"""

    bluetooth_radio_supported: bool = betterproto.bool_field(403)
    """Does the device have a Bluetooth (classic) radio?"""

    bluetooth_radio_enabled: bool = betterproto.bool_field(404)
    """Is the Bluetooth (classic) radio on?"""

    mobile_data_supported: bool = betterproto.bool_field(405)
    """Does the device hardware support a mobile data connection?"""

    tethering_supported: bool = betterproto.bool_field(406)
    """Does the device support tethering?"""

    ble_radio_supported: bool = betterproto.bool_field(407)
    """Does the device have a BLE radio?"""

    pixel_experience: bool = betterproto.bool_field(408)
    """Is the device a "Pixel Experience" Android device?"""

    arc_plus_plus: bool = betterproto.bool_field(409)
    """Is the device running in the ARC++ container on a chromebook?"""

    is_screenlock_state_flaky: bool = betterproto.bool_field(410)
    """
    Is the value set in |using_secure_screenlock| reliable? On some Android
     devices, the platform API to get the screenlock state is not trustworthy.
     See b/32212161.
    """

    supported_software_features: List["SoftwareFeature"] = betterproto.enum_field(411)
    """A list of multi-device software features supported by the device."""

    enabled_software_features: List["SoftwareFeature"] = betterproto.enum_field(412)
    """
    A list of multi-device software features currently enabled (active) on the
     device.
    """

    enrollment_session_id: bytes = betterproto.bytes_field(1000)
    """The enrollment session id this is sent with"""

    oauth_token: str = betterproto.string_field(1001)
    """A copy of the user's OAuth token"""


@dataclass(eq=False, repr=False)
class GcmMetadata(betterproto.Message):
    type: "Type" = betterproto.enum_field(1)
    version: int = betterproto.int32_field(2)


@dataclass(eq=False, repr=False)
class Tickle(betterproto.Message):
    expiry_time: int = betterproto.fixed64_field(1)
    """Time after which this tickle should expire"""


@dataclass(eq=False, repr=False)
class LoginNotificationInfo(betterproto.Message):
    creation_time: int = betterproto.fixed64_field(2)
    """Time at which the server received the login notification request."""

    email: str = betterproto.string_field(3)
    """Must correspond to user_id in LoginNotificationRequest, if set."""

    host: str = betterproto.string_field(4)
    """Host where the user's credentials were used to login, if meaningful."""

    source: str = betterproto.string_field(5)
    """Location from where the user's credentials were used, if meaningful."""

    event_type: str = betterproto.string_field(6)
    """Type of login, e.g. ssh, gnome-screensaver, or web."""


@dataclass(eq=False, repr=False)
class Ukey2Message(betterproto.Message):
    message_type: "Ukey2MessageType" = betterproto.enum_field(1)
    message_data: bytes = betterproto.bytes_field(2)


@dataclass(eq=False, repr=False)
class Ukey2Alert(betterproto.Message):
    type: "Ukey2AlertAlertType" = betterproto.enum_field(1)
    error_message: str = betterproto.string_field(2)


@dataclass(eq=False, repr=False)
class Ukey2ClientInit(betterproto.Message):
    version: int = betterproto.int32_field(1)
    random: bytes = betterproto.bytes_field(2)
    """protection"""

    cipher_commitments: List["Ukey2ClientInitCipherCommitment"] = (
        betterproto.message_field(3)
    )
    next_protocol: str = betterproto.string_field(4)
    """Next protocol that the client wants to speak."""


@dataclass(eq=False, repr=False)
class Ukey2ClientInitCipherCommitment(betterproto.Message):
    """
    One commitment (hash of ClientFinished containing public key) per supported
     cipher
    """

    handshake_cipher: "Ukey2HandshakeCipher" = betterproto.enum_field(1)
    commitment: bytes = betterproto.bytes_field(2)


@dataclass(eq=False, repr=False)
class Ukey2ServerInit(betterproto.Message):
    version: int = betterproto.int32_field(1)
    random: bytes = betterproto.bytes_field(2)
    """protection"""

    handshake_cipher: "Ukey2HandshakeCipher" = betterproto.enum_field(3)
    """Selected Cipher and corresponding public key"""

    public_key: bytes = betterproto.bytes_field(4)


@dataclass(eq=False, repr=False)
class Ukey2ClientFinished(betterproto.Message):
    public_key: bytes = betterproto.bytes_field(1)
