import socket as _socket

from pyquickshare.rfcomm._rfcomm import (  # pyright: ignore[reportMissingModuleSource]
    AF_BLUETOOTH,
    BT_SECURITY,
    BT_SECURITY_FIPS,
    BT_SECURITY_HIGH,
    BT_SECURITY_LOW,
    BT_SECURITY_MEDIUM,
    BT_SECURITY_SDP,
    BTPROTO_RFCOMM,
    PF_BLUETOOTH,
    RFCOMM_CONNINFO,
    RFCOMM_DEFAULT_MTU,
    RFCOMM_LM,
    RFCOMM_LM_AUTH,
    RFCOMM_LM_ENCRYPT,
    RFCOMM_LM_MASTER,
    RFCOMM_LM_RELIABLE,
    RFCOMM_LM_SECURE,
    RFCOMM_LM_TRUSTED,
    RFCOMM_PSM,
    SHUT_RD,
    SHUT_RDWR,
    SHUT_WR,
    SOCK_SEQPACKET,
    SOCK_STREAM,
    SOL_BLUETOOTH,
    SOL_RFCOMM,
    ba2str,
    bacmp,
    bacpy,
    bdaddr_t,
    bind_rfcomm,
    bt_security,
    connect_rfcomm,
    find_rfcomm_channel,
    getsockopt_bytes,
    make_rfcomm_socket,
    rfcomm_conninfo,
    setsockopt_bytes,
    sockaddr_rc,
    str2ba,
)

__all__ = [
    "AF_BLUETOOTH",
    "BTPROTO_RFCOMM",
    "BT_SECURITY",
    "BT_SECURITY_FIPS",
    "BT_SECURITY_HIGH",
    "BT_SECURITY_LOW",
    "BT_SECURITY_MEDIUM",
    "BT_SECURITY_SDP",
    "PF_BLUETOOTH",
    "RFCOMM_CONNINFO",
    "RFCOMM_DEFAULT_MTU",
    "RFCOMM_LM",
    "RFCOMM_LM_AUTH",
    "RFCOMM_LM_ENCRYPT",
    "RFCOMM_LM_MASTER",
    "RFCOMM_LM_RELIABLE",
    "RFCOMM_LM_SECURE",
    "RFCOMM_LM_TRUSTED",
    "RFCOMM_PSM",
    "SHUT_RD",
    "SHUT_RDWR",
    "SHUT_WR",
    "SOCK_SEQPACKET",
    "SOCK_STREAM",
    "SOL_BLUETOOTH",
    "SOL_RFCOMM",
    "ba2str",
    "bacmp",
    "bacpy",
    "bdaddr_t",
    "bind_rfcomm",
    "bt_security",
    "connect_rfcomm",
    "find_rfcomm_channel",
    "getsockopt_bytes",
    "make_rfcomm_socket",
    "open_rfcomm_socket",
    "rfcomm_conninfo",
    "setsockopt_bytes",
    "sockaddr_rc",
    "str2ba",
]


def open_rfcomm_socket() -> _socket.socket:
    fd = make_rfcomm_socket()
    return _socket.socket(fileno=fd)
