# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: sharing_enums.proto
# plugin: python-betterproto
# This file has been @generated

from dataclasses import dataclass

import betterproto


class EventType(betterproto.Enum):
    """
    We use event based logging (an event object can be constructed and logged
     immediately when they occur). To obtain session based information (e.g.
     durations, counting incoming introductions), we use flowId (sender/receiver)
     in NearbyClearcutLogger (for android, or clearcut_event_logger as the
     equivalence for Windows) for all events (may exclude settings), and
     session_id for a pair of events (start and end of a session).
     Next id: 74
    """

    _ = 0
    ACCEPT_AGREEMENTS = 1
    """
    When new users accept agreements (like grant permission to contacts for
     CONTACT_ONLY visibility) and are enrolled into Nearby Sharing. This event
     is used to count number of new users.
    """

    ENABLE_NEARBY_SHARING = 2
    """User enables/disables nearby sharing from setting or tile service."""

    SET_VISIBILITY = 3
    """User sets visibility preference from setting."""

    DESCRIBE_ATTACHMENTS = 4
    """
    Describe attachments immediately when Nearby Sharing is opened by another
     app which is used to generate/attach attachments to be shared with other
     devices.
    """

    SCAN_FOR_SHARE_TARGETS_START = 5
    """Start of a scanning phase at sender."""

    SCAN_FOR_SHARE_TARGETS_END = 6
    """End of the scanning phase at sender."""

    ADVERTISE_DEVICE_PRESENCE_START = 7
    """Receiver advertises itself for presence (a pseudo session)."""

    ADVERTISE_DEVICE_PRESENCE_END = 8
    """End of the advertising phase at receiver."""

    SEND_FAST_INITIALIZATION = 9
    """Sender sends a fast initialization to receiver."""

    RECEIVE_FAST_INITIALIZATION = 10
    """Receiver receives the fast initialization."""

    DISCOVER_SHARE_TARGET = 11
    """Sender discovers a share target."""

    SEND_INTRODUCTION = 12
    """Sender sends introduction (before attachments being sent)."""

    RECEIVE_INTRODUCTION = 13
    """Receiver receives introduction."""

    RESPOND_TO_INTRODUCTION = 14
    """
    Receiver responds to introduction (before attachments being sent).
     Actions: Accept, Reject, or (for some reason) Fail.
    """

    SEND_ATTACHMENTS_START = 15
    """Start of the sending attachments phase at sender."""

    SEND_ATTACHMENTS_END = 16
    """End of sending attachments phase at sender."""

    RECEIVE_ATTACHMENTS_START = 17
    """Start of the receiving attachments phase at receiver."""

    RECEIVE_ATTACHMENTS_END = 18
    """End of receiving attachments phase at receiver."""

    CANCEL_SENDING_ATTACHMENTS = 19
    """Sender cancels sending attachments."""

    CANCEL_RECEIVING_ATTACHMENTS = 20
    """Receiver cancels receiving attachments."""

    OPEN_RECEIVED_ATTACHMENTS = 21
    """Receiver opens received attachments."""

    LAUNCH_SETUP_ACTIVITY = 22
    """User opens the setup activity."""

    ADD_CONTACT = 23
    """User adds a contact."""

    REMOVE_CONTACT = 24
    """User removes a contact."""

    FAST_SHARE_SERVER_RESPONSE = 25
    """Local devices all Fast Share server."""

    SEND_START = 26
    """The start of a sending session."""

    ACCEPT_FAST_INITIALIZATION = 27
    """Receiver accepts a fast initialization."""

    SET_DATA_USAGE = 28
    """Set data usage preference."""

    DISMISS_FAST_INITIALIZATION = 29
    """Receiver dismisses a fast initialization"""

    CANCEL_CONNECTION = 30
    """Cancel connection."""

    LAUNCH_ACTIVITY = 31
    """
    User starts a chimera activity (e.g. ConsentsChimeraActivity,
     DeviceVisibilityChimeraActivity...)
    """

    DISMISS_PRIVACY_NOTIFICATION = 32
    """Receiver dismisses a privacy notification."""

    TAP_PRIVACY_NOTIFICATION = 33
    """Receiver taps a privacy notification."""

    TAP_HELP = 34
    """Receiver taps a help page."""

    TAP_FEEDBACK = 35
    """Receiver taps a feedback."""

    ADD_QUICK_SETTINGS_TILE = 36
    """Receiver adds quick settings tile."""

    REMOVE_QUICK_SETTINGS_TILE = 37
    """Receiver removes quick settings tile."""

    LAUNCH_PHONE_CONSENT = 38
    """Receiver phone consent clicked."""

    DISPLAY_PHONE_CONSENT = 54
    """Devices show a phone consent banner in Nearby Share Settings"""

    TAP_QUICK_SETTINGS_TILE = 39
    """Receiver taps quick settings tile."""

    INSTALL_APK = 40
    """Receiver Installation of APKs status."""

    VERIFY_APK = 41
    """Receiver verification of APKs status."""

    LAUNCH_CONSENT = 42
    """User starts a consent."""

    PROCESS_RECEIVED_ATTACHMENTS_END = 43
    """
    After receiving payloads, Nearby Share still needs to transfer the payloads
     to correct attachment formats and move files attachments from temporary
     directory to final destination.
    """

    TOGGLE_SHOW_NOTIFICATION = 44
    """Toggle Show Notification setting item in Nearby Share setting."""

    SET_DEVICE_NAME = 45
    """Set device name"""

    DECLINE_AGREEMENTS = 46
    """users dropped off opt-in page."""

    REQUEST_SETTING_PERMISSIONS = 47
    """Request setting permissions (Wifi/BT/location/airplane mode)."""

    ESTABLISH_CONNECTION = 48
    """Set up a connection with the remote device."""

    DEVICE_SETTINGS = 49
    """Track device states in Nearby Share setting."""

    AUTO_DISMISS_FAST_INITIALIZATION = 50
    """Receiver auto dismisses a fast initialization notification."""

    APP_CRASH = 51
    """
    App Crash event.
     Used only for Windows App now.
    """

    TAP_QUICK_SETTINGS_FILE_SHARE = 52
    """Sender taps the Send button in quick settings"""

    DISPLAY_PRIVACY_NOTIFICATION = 53
    """Devices show a privacy notification"""

    PREFERENCES_USAGE = 55
    """
    Preference usage event (e.g. load/save preferences, etc).
     Used only for Windows App now.
    """

    DEFAULT_OPT_IN = 56
    """Default opt in"""

    SETUP_WIZARD = 57
    """The result of the setup wizard flow"""

    TAP_QR_CODE = 58
    """Sender taps a QR code"""

    QR_CODE_LINK_SHOWN = 59
    """QR code link shown"""

    PARSING_FAILED_ENDPOINT_ID = 60
    """Sender failed to parse endpoint id."""

    FAST_INIT_DISCOVER_DEVICE = 61
    """The device is discovered by fast initialization"""

    SEND_DESKTOP_NOTIFICATION = 62
    """Send desktop notification."""

    SET_ACCOUNT = 63
    """User sets account preference"""

    DECRYPT_CERTIFICATE_FAILURE = 64
    """Decrypt certificate failure"""

    SHOW_ALLOW_PERMISSION_AUTO_ACCESS = 65
    """Show allow permission auto access UI"""

    SEND_DESKTOP_TRANSFER_EVENT = 66
    """
    UI events for transferring files with desktop applications. It includes
     event types such as DESKTOP_TRANSFER_EVENT_SEND_TYPE_SELECT_A_DEVICE.
    """

    WAITING_FOR_ACCEPT = 67
    """Show accept button on Quick Share receive UI"""

    HIGH_QUALITY_MEDIUM_SETUP = 68
    """High quality event setup"""

    RPC_CALL_STATUS = 69
    """RPC call status"""

    START_QR_CODE_SESSION = 70
    """A QR code sharing session has started"""

    QR_CODE_OPENED_IN_WEB_CLIENT = 71
    """
    A QR code URL has been opened in a web client/browser instead of in a
     native Quick Share app.
    """

    HATS_JOINT_EVENT = 72
    """A HaTS survey session id has been joined with Quick Share flow id."""

    RECEIVE_PREVIEWS = 73
    """Previews received."""


class EventCategory(betterproto.Enum):
    """
    Event category to differentiate whether this comes from sender or receiver,
     whether this is for communication flow, or for settings.
    """

    _ = 0
    SENDING_EVENT = 1
    RECEIVING_EVENT = 2
    SETTINGS_EVENT = 3
    RPC_EVENT = 4


class NearbySharingStatus(betterproto.Enum):
    """Status of nearby sharing."""

    _ = 0
    ON = 1
    OFF = 2


class Visibility(betterproto.Enum):
    _ = 0
    CONTACTS_ONLY = 1
    EVERYONE = 2
    SELECTED_CONTACTS_ONLY = 3
    HIDDEN = 4
    SELF_SHARE = 5


class DataUsage(betterproto.Enum):
    _ = 0
    ONLINE = 1
    WIFI_ONLY = 2
    OFFLINE = 3


class EstablishConnectionStatus(betterproto.Enum):
    """
    The status of establishing a connection. Used by ESTABLISH_CONNECTION.
    """

    CONNECTION_STATUS_UNKNOWN = 0
    CONNECTION_STATUS_SUCCESS = 1
    CONNECTION_STATUS_FAILURE = 2
    CONNECTION_STATUS_CANCELLATION = 3
    CONNECTION_STATUS_MEDIA_UNAVAILABLE_ATTACHMENT = 4
    CONNECTION_STATUS_FAILED_PAIRED_KEYHANDSHAKE = 5
    CONNECTION_STATUS_FAILED_WRITE_INTRODUCTION = 6
    CONNECTION_STATUS_FAILED_NULL_CONNECTION = 7
    CONNECTION_STATUS_FAILED_NO_TRANSFER_UPDATE_CALLBACK = 8
    CONNECTION_STATUS_LOST_CONNECTIVITY = 9
    CONNECTION_STATUS_INVALID_ADVERTISEMENT = 10
    """
    TODO: b/341782941 - : Annote this status when it's confirmed by Nearby
     Connections team.
    """


class AttachmentTransmissionStatus(betterproto.Enum):
    """
    The status of sending and receiving attachments. Used by SEND_ATTACHMENTS.
    """

    _ = 0
    _ = 1
    _ = 2
    _ = 3
    REJECTED_ATTACHMENT = 4
    TIMED_OUT_ATTACHMENT = 5
    AWAITING_REMOTE_ACCEPTANCE_FAILED_ATTACHMENT = 6
    NOT_ENOUGH_SPACE_ATTACHMENT = 7
    FAILED_NO_TRANSFER_UPDATE_CALLBACK = 8
    MEDIA_UNAVAILABLE_ATTACHMENT = 9
    UNSUPPORTED_ATTACHMENT_TYPE_ATTACHMENT = 10
    NO_ATTACHMENT_FOUND = 11
    FAILED_NO_SHARE_TARGET_ENDPOINT = 12
    FAILED_PAIRED_KEYHANDSHAKE = 13
    FAILED_NULL_CONNECTION = 14
    FAILED_NO_PAYLOAD = 15
    FAILED_WRITE_INTRODUCTION = 16
    FAILED_UNKNOWN_REMOTE_RESPONSE = 17
    """The remote response is either missing or has an unknown type."""

    FAILED_NULL_CONNECTION_INIT_OUTGOING = 18
    """Breakdowns of FAILED_NULL_CONNECTION (Desktop side)"""

    FAILED_NULL_CONNECTION_DISCONNECTED = 19
    FAILED_NULL_CONNECTION_LOST_CONNECTIVITY = 20
    """
    Breakdowns of FAILED_NULL_CONNECTION (android side)
     Connection failed due to Wifi is disconnected or Bluetooth setting is off
     or user turn on airplane mode.
    """

    FAILED_NULL_CONNECTION_FAILURE = 21
    """Unexpected connection failure."""

    _ = 22
    _ = 23
    _ = 24
    _ = 25
    FAILED_UNKNOWN_REMOTE_RESPONSE_TRANSMISSION_STATUS = 26
    NO_RESPONSE_FRAME_CONNECTION_CLOSED_LOST_CONNECTIVITY_TRANSMISSION_STATUS = 27
    """
    Connection failed due to Wifi is disconnected or Bluetooth setting is off
     or user turn on airplane mode.
    """

    NO_RESPONSE_FRAME_CONNECTION_CLOSED_TRANSMISSION_STATUS = 28
    """Unexpected connection failure due to no response frame."""

    LOST_CONNECTIVITY_TRANSMISSION_STATUS = 29
    """
    Connection failed due to Wifi is disconnected or Bluetooth setting is off
     or user turn on airplane mode.
    """

    FAILED_DISALLOWED_MEDIUM = 30
    """Connection failed due to the medium is not allowed."""


class ConnectionLayerStatus(betterproto.Enum):
    """Generic result status of NearbyConnections API calls."""

    UNKNOWN = 0
    """No status is available"""

    SUCCESS = 1
    """The operation was successful."""

    ERROR = 2
    """The operation failed, without any more information."""

    OUT_OF_ORDER_API_CALL = 3
    """
    The app called an API method out of order (i.e. another method is expected
     to be called first).
    """

    ALREADY_HAVE_ACTIVE_STRATEGY = 4
    """
    The app already has active operations (advertising, discovering, or
     connected to other devices) with another Strategy. Stop these operations on
     the current Strategy before trying to advertise or discover with a new
     Strategy.
    """

    ALREADY_ADVERTISING = 5
    """
    The app is already advertising; call StopAdvertising() before trying to
     advertise again.
    """

    ALREADY_DISCOVERING = 6
    """
    The app is already discovering; call StopDiscovery() before trying to
     discover again.
    """

    ALREADY_LISTENING = 7
    """
    NC is already listening for incoming connections from remote endpoints.
    """

    END_POINT_IO_ERROR = 8
    """
    An attempt to read from/write to a connected remote endpoint failed. If
     this occurs repeatedly, consider invoking DisconnectFromEndpoint().
    """

    END_POINT_UNKNOWN = 9
    """
    An attempt to interact with a remote endpoint failed because it's unknown
     to us -- it's either an endpoint that was never discovered, or an endpoint
     that never connected to us (both of which are indicative of bad input from
     the client app).
    """

    CONNECTION_REJECTED = 10
    """The remote endpoint rejected the connection request."""

    ALREADY_CONNECTED_TO_END_POINT = 11
    """
    The app is already connected to the specified endpoint. Multiple
     connections to a remote endpoint cannot be maintained simultaneously.
    """

    NOT_CONNECTED_TO_END_POINT = 12
    """The remote endpoint is not connected; messages cannot be sent to it."""

    BLUETOOTH_ERROR = 13
    """
    There was an error trying to use the device's Bluetooth capabilities.
    """

    BLE_ERROR = 14
    """
    There was an error trying to use the device's Bluetooth Low Energy
     capabilities.
    """

    WIFI_LAN_ERROR = 15
    """There was an error trying to use the device's Wi-Fi capabilities."""

    PAYLOAD_UNKNOWN = 16
    """
    An attempt to interact with an in-flight Payload failed because it's
     unknown to us.
    """

    RESET = 17
    """The connection was reset"""

    TIMEOUT = 18
    """The connection timed out"""


class ProcessReceivedAttachmentsStatus(betterproto.Enum):
    """
    The status of processing attachments after receiver received payloads
     successfully.
    """

    PROCESSING_STATUS_UNKNOWN = 0
    PROCESSING_STATUS_COMPLETE_PROCESSING_ATTACHMENTS = 1
    PROCESSING_STATUS_FAILED_MOVING_FILES = 2
    PROCESSING_STATUS_FAILED_RECEIVING_APK = 3
    PROCESSING_STATUS_FAILED_RECEIVING_TEXT = 4
    PROCESSING_STATUS_FAILED_RECEIVING_WIFI_CREDENTIALS = 5


class SessionStatus(betterproto.Enum):
    """
    The status of advertising and discovering sessions. Used by
     SCAN_FOR_SHARE_TARGETS and ADVERTISE_DEVICE_PRESENCE.
    """

    _ = 0
    _ = 1
    _ = 2
    """
    TODO: b/341782941 - FAILED_SESSION_STATUS occurs when the status of
     advertising or discovering sessions is not successful. It can be
     due to STATUS_INTERNAL_ERROR, STATUS_INTERRUPTION, STATUS_CANCELLED.
     More session statuses should be logged to determine the status.
    """


class ResponseToIntroduction(betterproto.Enum):
    """User's response to introductions."""

    _ = 0
    ACCEPT_INTRODUCTION = 1
    REJECT_INTRODUCTION = 2
    FAIL_INTRODUCTION = 3


class DeviceType(betterproto.Enum):
    """
    TODO(fdi): may eventually include desktop, etc.
     The type of a remote device.
    """

    _ = 0
    PHONE = 1
    TABLET = 2
    LAPTOP = 3
    CAR = 4
    FOLDABLE = 5
    XR = 6


class OsType(betterproto.Enum):
    """
    TODO(fdi): may eventually include windows, iOS, etc.
     The OS type of a remote device.
    """

    _ = 0
    ANDROID = 1
    CHROME_OS = 2
    IOS = 3
    WINDOWS = 4
    MACOS = 5


class DeviceRelationship(betterproto.Enum):
    """Relationship of remote device to sender device."""

    _ = 0
    IS_SELF = 1
    """The remote device belongs to the same owner as sender device."""

    IS_CONTACT = 2
    """The remote device is a contact of sender."""

    IS_STRANGER = 3
    """The remote device is a stranger."""


class LogSource(betterproto.Enum):
    """The device sources of the clearcut log."""

    UNSPECIFIED_SOURCE = 0
    LAB_DEVICES = 1
    """Represents the devices in Nearby labs."""

    INTERNAL_DEVICES = 2
    """
    Represents the devices tested by Nearby engs, in the long term can include
     any devices with newest feature flags.
    """

    BETA_TESTER_DEVICES = 3
    """
    Represents the devices testing our in-development features before they're
     released to the greater public.
    """

    OEM_DEVICES = 4
    """
    Represents the OEM partners (like Samsung) that we're working with to
     verify functionality on their devices.
    """

    DEBUG_DEVICES = 5
    """Represents the device for debugging."""

    NEARBY_MODULE_FOOD_DEVICES = 6
    """Represents the device for Nearby Module Food."""

    BETO_DOGFOOD_DEVICES = 7
    """Represents the device for BeTo Team Food."""

    NEARBY_DOGFOOD_DEVICES = 8
    """Represents the device for Nearby dog Food."""

    NEARBY_TEAMFOOD_DEVICES = 9
    """Represents the device for Nearby Team Food."""


class ServerActionName(betterproto.Enum):
    """The Fast Share server action name."""

    UNKNOWN_SERVER_ACTION = 0
    UPLOAD_CERTIFICATES = 1
    DOWNLOAD_CERTIFICATES = 2
    CHECK_REACHABILITY = 3
    UPLOAD_CONTACTS = 4
    UPDATE_DEVICE_NAME = 5
    UPLOAD_SENDER_CERTIFICATES = 6
    DOWNLOAD_SENDER_CERTIFICATES = 7
    UPLOAD_CONTACTS_AND_CERTIFICATES = 8
    LIST_REACHABLE_PHONE_NUMBERS = 9
    LIST_MY_DEVICES = 10
    LIST_CONTACT_PEOPLE = 11
    DOWNLOAD_CERTIFICATES_INFO = 12
    """used for analytics logger to record action name."""


class ServerResponseState(betterproto.Enum):
    """The Fast Share server response state."""

    _ = 0
    SERVER_RESPONSE_SUCCESS = 1
    SERVER_RESPONSE_UNKNOWN_FAILURE = 2
    SERVER_RESPONSE_STATUS_OTHER_FAILURE = 3
    """For StatusException."""

    SERVER_RESPONSE_STATUS_DEADLINE_EXCEEDED = 4
    SERVER_RESPONSE_STATUS_PERMISSION_DENIED = 5
    SERVER_RESPONSE_STATUS_UNAVAILABLE = 6
    SERVER_RESPONSE_STATUS_UNAUTHENTICATED = 7
    SERVER_RESPONSE_STATUS_INVALID_ARGUMENT = 9
    SERVER_RESPONSE_GOOGLE_AUTH_FAILURE = 8
    """For GoogleAuthException."""

    SERVER_RESPONSE_NOT_CONNECTED_TO_INTERNET = 10
    """For Internet connect status."""


class SyncPurpose(betterproto.Enum):
    """The purpose of requesting the server request."""

    UNKNOWN = 0
    ON_DEMAND_SYNC = 1
    """When NearbySharingChimeraService#sync() is called."""

    CHIME_NOTIFICATION = 2
    """Requested by chime notification."""

    DAILY_SYNC = 3
    """For reqular daily sync."""

    OPT_IN_FIRST_SYNC = 4
    """Wen a device opts into Nearby Share."""

    CHECK_DEFAULT_OPT_IN = 5
    """
    Requested when Nearby Share automatically enables a device that shares
     a single account that has already opted in on another device.
    """

    NEARBY_SHARE_ENABLED = 6
    """When a device enables Nearby Share."""

    SYNC_AT_FAST_INIT = 7
    """When a device is in fast init advertising."""

    SYNC_AT_DISCOVERY = 8
    """When device start discovery."""

    SYNC_AT_LOAD_PRIVATE_CERTIFICATE = 9
    """When device tries to load valid private certificate."""

    SYNC_AT_ADVERTISEMENT = 10
    """When device start advertiseement."""

    CONTACT_LIST_CHANGE = 11
    """When device contacts list changes."""

    SHOW_C11N_VIEW = 12
    """When showing the C11 banner in Neary Share setting."""

    REGULAR_CHECK_CONTACT_REACHABILITY = 13
    """For regular check contact reachability."""

    VISIBILITY_SELECTED_CONTACT_CHANGE = 14
    """When selected contacts list changes in visibility setting."""

    ACCOUNT_CHANGE = 15
    """When switching account."""

    REGENERATE_CERTIFICATES = 16
    """When regenerate certificates"""

    DEVICE_CONTACTS_CONSENT_CHANGE = 17
    """When Device Contacts consent changes"""


class ClientRole(betterproto.Enum):
    """The device role to trigger the server request."""

    UNKNOWN = 0
    SENDER = 1
    RECEIVER = 2


class ScanType(betterproto.Enum):
    """The type of Nearby Sharing scanning."""

    _ = 0
    FOREGROUND_SCAN = 1
    FOREGROUND_RETRY_SCAN = 2
    DIRECT_SHARE_SCAN = 3
    BACKGROUND_SCAN = 4


class ParsingFailedType(betterproto.Enum):
    """The type of parsing endpoint id failed type."""

    FAILED_UNKNOWN_TYPE = 0
    FAILED_PARSE_ADVERTISEMENT = 1
    """
    NULL advertisement is returned due to sender failing to parse advertisement
     from endpointInfo byte stream from receiver advertisement.
    """

    FAILED_CONVERT_SHARE_TARGET = 2
    """
    NULL shareTarget is returned due to sender failing to create shareTarget
     from a valid parsed advertisement stemming from issues in certificates, QR
     code tokens or device names.
    """


class AdvertisingMode(betterproto.Enum):
    """The Nearby Sharing advertising mode."""

    _ = 0
    _ = 1
    _ = 2
    _ = 3
    _ = 4
    _ = 5


class DiscoveryMode(betterproto.Enum):
    """The Nearby Sharing discovery mode."""

    _ = 0
    _ = 1
    _ = 2
    _ = 3
    _ = 4
    _ = 5


class ActivityName(betterproto.Enum):
    """The class name of chimera activity."""

    UNKNOWN_ACTIVITY = 0
    SHARE_SHEET_ACTIVITY = 1
    SETTINGS_ACTIVITY = 2
    RECEIVE_SURFACE_ACTIVITY = 3
    SETUP_ACTIVITY = 4
    DEVICE_VISIBILITY_ACTIVITY = 5
    CONSENTS_ACTIVITY = 6
    SET_DEVICE_NAME_DIALOG = 7
    SET_DATA_USAGE_DIALOG = 8
    QUICK_SETTINGS_ACTIVITY = 9
    REMOTE_COPY_SHARE_SHEET_ACTIVITY = 10
    SETUP_WIZARD_ACTIVITY = 11
    SETTINGS_REVIEW_ACTIVITY = 12


class ConsentType(betterproto.Enum):
    """The type of consent page user launches."""

    UNKNOWN = 0
    C11N = 1
    """launch Constellation consent page."""

    DEVICE_CONTACT = 2
    """launch device contact consent page."""


class ConsentAcceptanceStatus(betterproto.Enum):
    CONSENT_UNKNOWN_ACCEPT_STATUS = 0
    CONSENT_ACCEPTED = 1
    CONSENT_DECLINED = 2
    CONSENT_UNABLE_TO_ENABLE = 3
    """unable to enable consent."""


class ApkSource(betterproto.Enum):
    _ = 0
    APK_FROM_SD_CARD = 1
    INSTALLED_APP = 2


class InstallApkStatus(betterproto.Enum):
    """The Installation status of APK."""

    _ = 0
    FAIL_INSTALLATION = 1
    SUCCESS_INSTALLATION = 2


class VerifyApkStatus(betterproto.Enum):
    """The verification status of APK."""

    _ = 0
    NOT_INSTALLABLE = 1
    INSTALLABLE = 2
    ALREADY_INSTALLED = 3


class ShowNotificationStatus(betterproto.Enum):
    _ = 0
    SHOW = 1
    NOT_SHOW = 2


class PermissionRequestResult(betterproto.Enum):
    PERMISSION_UNKNOWN_REQUEST_RESULT = 0
    PERMISSION_GRANTED = 1
    PERMISSION_REJECTED = 2
    PERMISSION_UNABLE_TO_GRANT = 3


class PermissionRequestType(betterproto.Enum):
    PERMISSION_UNKNOWN_TYPE = 0
    PERMISSION_AIRPLANE_MODE_OFF = 1
    PERMISSION_WIFI = 2
    PERMISSION_BLUETOOTH = 3
    PERMISSION_LOCATION = 4
    PERMISSION_WIFI_HOTSPOT = 5


class SharingUseCase(betterproto.Enum):
    USE_CASE_UNKNOWN = 0
    USE_CASE_NEARBY_SHARE = 1
    USE_CASE_REMOTE_COPY_PASTE = 2
    USE_CASE_WIFI_CREDENTIAL = 3
    USE_CASE_APP_SHARE = 4
    USE_CASE_QUICK_SETTING_FILE_SHARE = 5
    USE_CASE_SETUP_WIZARD = 6
    USE_CASE_NEARBY_SHARE_WITH_QR_CODE = 7
    """
    Deprecated. QR code is an addition to existing use cases rather than being
     a separate use case.
    """

    USE_CASE_REDIRECTED_FROM_BLUETOOTH_SHARE = 8
    """The user was redirected from Bluetooth sharing UI to Nearby Share"""


class AppCrashReason(betterproto.Enum):
    """Used only for Windows App now."""

    UNKNOWN = 0


class AttachmentSourceType(betterproto.Enum):
    """
    Thes source where the attachemnt comes from. It can be an action, app name,
     etc. The first 6 source types are being used as FileSenderType in Nearby
     Share Windows app.
    """

    ATTACHMENT_SOURCE_UNKNOWN = 0
    ATTACHMENT_SOURCE_CONTEXT_MENU = 1
    ATTACHMENT_SOURCE_DRAG_AND_DROP = 2
    ATTACHMENT_SOURCE_SELECT_FILES_BUTTON = 3
    ATTACHMENT_SOURCE_PASTE = 4
    ATTACHMENT_SOURCE_SELECT_FOLDERS_BUTTON = 5
    ATTACHMENT_SOURCE_SHARE_ACTIVATION = 6


class PreferencesAction(betterproto.Enum):
    """
    The action to interact with preferences.
     Used only for Windows App now.
    """

    UNKNOWN = 0
    NO_ACTION = 1
    LOAD_PREFERENCES = 2
    """Primary actions/functions towards preferences"""

    SAVE_PREFERENCESS = 3
    ATTEMPT_LOAD = 4
    RESTORE_FROM_BACKUP = 5
    CREATE_PREFERENCES_PATH = 6
    """Other actions within the 4 actions above"""

    MAKE_PREFERENCES_BACKUP_FILE = 7
    CHECK_IF_PREFERENCES_PATH_EXISTS = 8
    CHECK_IF_PREFERENCES_INPUT_STREAM_STATUS = 9
    CHECK_IF_PREFERENCES_FILE_IS_CORRUPTED = 10
    CHECK_IF_PREFERENCES_BACKUP_FILE_EXISTS = 11


class PreferencesActionStatus(betterproto.Enum):
    """
    The status of the action to interact with preferences.
     Used only for Windows App now.
    """

    UNKNOWN = 0
    SUCCESS = 1
    FAIL = 2


class FastInitState(betterproto.Enum):
    """* The distance of the found nearby fast init advertisement."""

    FAST_INIT_UNKNOWN_STATE = 0
    FAST_INIT_CLOSE_STATE = 1
    """
    A device was found in close proximity.
     distance < fast_init_distance_close_centimeters(50 cm)
    """

    FAST_INIT_FAR_STATE = 2
    """
    A device was found in far proximity.
     distance < fast_init_distance_close_centimeters(10 m)
    """

    FAST_INIT_LOST_STATE = 3
    """No devices have been found nearby. The default state."""


class FastInitType(betterproto.Enum):
    """* The type of FastInit advertisement."""

    FAST_INIT_UNKNOWN_TYPE = 0
    FAST_INIT_NOTIFY_TYPE = 1
    """Show HUN to notify the user."""

    FAST_INIT_SILENT_TYPE = 2
    """Not notify the user."""


class DesktopNotification(betterproto.Enum):
    """* The type of desktop notification event."""

    UNKNOWN = 0
    CONNECTING = 1
    PROGRESS = 2
    ACCEPT = 3
    RECEIVED = 4
    ERROR = 5


class DesktopTransferEventType(betterproto.Enum):
    UNKNOWN = 0
    DESKTOP_TRANSFER_EVENT_RECEIVE_TYPE_ACCEPT = 1
    """Receive attachments."""

    DESKTOP_TRANSFER_EVENT_RECEIVE_TYPE_PROGRESS = 2
    DESKTOP_TRANSFER_EVENT_RECEIVE_TYPE_RECEIVED = 3
    DESKTOP_TRANSFER_EVENT_RECEIVE_TYPE_ERROR = 4
    DESKTOP_TRANSFER_EVENT_SEND_TYPE_START = 5
    """Send attachments."""

    DESKTOP_TRANSFER_EVENT_SEND_TYPE_SELECT_A_DEVICE = 6
    DESKTOP_TRANSFER_EVENT_SEND_TYPE_PROGRESS = 7
    DESKTOP_TRANSFER_EVENT_SEND_TYPE_SENT = 8
    DESKTOP_TRANSFER_EVENT_SEND_TYPE_ERROR = 9


class DecryptCertificateFailureStatus(betterproto.Enum):
    DECRYPT_CERT_UNKNOWN_FAILURE = 0
    DECRYPT_CERT_NO_SUCH_ALGORITHM_FAILURE = 1
    DECRYPT_CERT_NO_SUCH_PADDING_FAILURE = 2
    DECRYPT_CERT_INVALID_KEY_FAILURE = 3
    DECRYPT_CERT_INVALID_ALGORITHM_PARAMETER_FAILURE = 4
    DECRYPT_CERT_ILLEGAL_BLOCK_SIZE_FAILURE = 5
    DECRYPT_CERT_BAD_PADDING_FAILURE = 6


class ContactAccess(betterproto.Enum):
    """Refer to go/qs-contacts-consent-2024 for the detail."""

    UNKNOWN = 0
    NO_CONTACT_UPLOADED = 1
    ONLY_UPLOAD_GOOGLE_CONTACT = 2
    UPLOAD_CONTACT_FOR_DEVICE_CONTACT_CONSENT = 3
    UPLOAD_CONTACT_FOR_QUICK_SHARE_CONSENT = 4


class IdentityVerification(betterproto.Enum):
    """Refer to go/qs-contacts-consent-2024 for the detail."""

    UNKNOWN = 0
    NO_PHONE_NUMBER_VERIFIED = 1
    PHONE_NUMBER_VERIFIED_NOT_LINKED_TO_GAIA = 2
    PHONE_NUMBER_VERIFIED_LINKED_TO_QS_GAIA = 3


class ButtonStatus(betterproto.Enum):
    UNKNOWN = 0
    CLICK_ACCEPT = 1
    CLICK_REJECT = 2
    IGNORE = 3
