# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: offline_wire_formats.proto
# plugin: python-betterproto
# This file has been @generated
import warnings
from dataclasses import dataclass
from typing import List, Optional

import betterproto


class OfflineFrameVersion(betterproto.Enum):
    UNKNOWN_VERSION = 0
    V1 = 1


class V1FrameFrameType(betterproto.Enum):
    UNKNOWN_FRAME_TYPE = 0
    CONNECTION_REQUEST = 1
    CONNECTION_RESPONSE = 2
    PAYLOAD_TRANSFER = 3
    BANDWIDTH_UPGRADE_NEGOTIATION = 4
    KEEP_ALIVE = 5
    DISCONNECTION = 6
    PAIRED_KEY_ENCRYPTION = 7


class ConnectionRequestFrameMedium(betterproto.Enum):
    """
    Should always match cs/symbol:location.nearby.proto.connections.Medium
     LINT.IfChange
    """

    UNKNOWN_MEDIUM = 0
    MDNS = 1
    BLUETOOTH = 2
    WIFI_HOTSPOT = 3
    BLE = 4
    WIFI_LAN = 5
    WIFI_AWARE = 6
    NFC = 7
    WIFI_DIRECT = 8
    WEB_RTC = 9
    BLE_L2CAP = 10
    USB = 11


class ConnectionResponseFrameResponseStatus(betterproto.Enum):
    """
    Used to replace the status integer parameter with a meaningful enum item.
     Map ConnectionsStatusCodes.STATUS_OK to ACCEPT and
     ConnectionsStatusCodes.STATUS_CONNECTION_REJECTED to REJECT.
     Flag: connection_replace_status_with_response_connectionResponseFrame
    """

    UNKNOWN_RESPONSE_STATUS = 0
    ACCEPT = 1
    REJECT = 2


class PayloadTransferFramePacketType(betterproto.Enum):
    UNKNOWN_PACKET_TYPE = 0
    DATA = 1
    CONTROL = 2


class PayloadTransferFramePayloadHeaderPayloadType(betterproto.Enum):
    UNKNOWN_PAYLOAD_TYPE = 0
    BYTES = 1
    FILE = 2
    STREAM = 3


class PayloadTransferFramePayloadChunkFlags(betterproto.Enum):
    LAST_CHUNK = 1


class PayloadTransferFrameControlMessageEventType(betterproto.Enum):
    UNKNOWN_EVENT_TYPE = 0
    PAYLOAD_ERROR = 1
    PAYLOAD_CANCELED = 2
    PAYLOAD_RECEIVED_ACK = 3


class BandwidthUpgradeNegotiationFrameEventType(betterproto.Enum):
    UNKNOWN_EVENT_TYPE = 0
    UPGRADE_PATH_AVAILABLE = 1
    LAST_WRITE_TO_PRIOR_CHANNEL = 2
    SAFE_TO_CLOSE_PRIOR_CHANNEL = 3
    CLIENT_INTRODUCTION = 4
    UPGRADE_FAILURE = 5
    CLIENT_INTRODUCTION_ACK = 6


class BandwidthUpgradeNegotiationFrameUpgradePathInfoMedium(betterproto.Enum):
    """
    Should always match cs/symbol:location.nearby.proto.connections.Medium
    """

    UNKNOWN_MEDIUM = 0
    MDNS = 1
    BLUETOOTH = 2
    WIFI_HOTSPOT = 3
    BLE = 4
    WIFI_LAN = 5
    WIFI_AWARE = 6
    NFC = 7
    WIFI_DIRECT = 8
    WEB_RTC = 9
    USB = 11
    """10 is reserved."""


class LocationStandardFormat(betterproto.Enum):
    UNKNOWN = 0
    E164_CALLING = 1
    """
    E164 country codes:
     https://en.wikipedia.org/wiki/List_of_country_calling_codes
     e.g. +1 for USA
    """

    ISO_3166_1_ALPHA_2 = 2
    """
    ISO 3166-1 alpha-2 country codes:
     https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2
    """


class OsInfoOsType(betterproto.Enum):
    UNKNOWN_OS_TYPE = 0
    ANDROID = 1
    CHROME_OS = 2
    WINDOWS = 3
    APPLE = 4
    LINUX = 100


@dataclass(eq=False, repr=False)
class OfflineFrame(betterproto.Message):
    version: "OfflineFrameVersion" = betterproto.enum_field(1)
    v1: "V1Frame" = betterproto.message_field(2)
    """
    Right now there's only 1 version, but if there are more, exactly one of
     the following fields will be set.
    """


@dataclass(eq=False, repr=False)
class V1Frame(betterproto.Message):
    type: "V1FrameFrameType" = betterproto.enum_field(1)
    connection_request: "ConnectionRequestFrame" = betterproto.message_field(2)
    """Exactly one of the following fields will be set."""

    connection_response: "ConnectionResponseFrame" = betterproto.message_field(3)
    payload_transfer: "PayloadTransferFrame" = betterproto.message_field(4)
    bandwidth_upgrade_negotiation: "BandwidthUpgradeNegotiationFrame" = (
        betterproto.message_field(5)
    )
    keep_alive: "KeepAliveFrame" = betterproto.message_field(6)
    disconnection: "DisconnectionFrame" = betterproto.message_field(7)
    paired_key_encryption: "PairedKeyEncryptionFrame" = betterproto.message_field(8)


@dataclass(eq=False, repr=False)
class ConnectionRequestFrame(betterproto.Message):
    endpoint_id: str = betterproto.string_field(1)
    endpoint_name: str = betterproto.string_field(2)
    handshake_data: bytes = betterproto.bytes_field(3)
    nonce: int = betterproto.int32_field(4)
    """
    A random number generated for each outgoing connection that is presently
     used to act as a tiebreaker when 2 devices connect to each other
     simultaneously; this can also be used for other initialization-scoped
     things in the future.
    """

    mediums: List["ConnectionRequestFrameMedium"] = betterproto.enum_field(5)
    """
    The mediums this device supports upgrading to. This list should be filtered
     by both the strategy and this device's individual limitations.
    """

    endpoint_info: bytes = betterproto.bytes_field(6)
    medium_metadata: "MediumMetadata" = betterproto.message_field(7)
    keep_alive_interval_millis: int = betterproto.int32_field(8)
    keep_alive_timeout_millis: int = betterproto.int32_field(9)
    device_type: int = betterproto.int32_field(10)
    """The type of {@link Device} object."""

    device_info: bytes = betterproto.bytes_field(11)
    """The bytes of serialized {@link Device} object."""


@dataclass(eq=False, repr=False)
class ConnectionResponseFrame(betterproto.Message):
    status: int = betterproto.int32_field(1)
    """
    One of:
    
     - ConnectionsStatusCodes.STATUS_OK
     - ConnectionsStatusCodes.STATUS_CONNECTION_REJECTED.
    """

    handshake_data: bytes = betterproto.bytes_field(2)
    response: "ConnectionResponseFrameResponseStatus" = betterproto.enum_field(3)
    os_info: "OsInfo" = betterproto.message_field(4)
    multiplex_socket_bitmask: int = betterproto.int32_field(5)
    """
    A bitmask value to indicate which medium supports Multiplex transmission
     feature. Each supporting medium could utilize one bit starting from the
     least significant bit in this field. eq. BT utilizes the LSB bit which 0x01
     means bt supports multiplex while 0x00 means not. Refer to ClientProxy.java
     for the bit usages.
    """

    nearby_connections_version: int = betterproto.int32_field(6)

    def __post_init__(self) -> None:
        super().__post_init__()
        if self.is_set("status"):
            warnings.warn(
                "ConnectionResponseFrame.status is deprecated", DeprecationWarning
            )


@dataclass(eq=False, repr=False)
class PayloadTransferFrame(betterproto.Message):
    packet_type: "PayloadTransferFramePacketType" = betterproto.enum_field(1)
    payload_header: "PayloadTransferFramePayloadHeader" = betterproto.message_field(2)
    payload_chunk: "PayloadTransferFramePayloadChunk" = betterproto.message_field(3)
    """
    Exactly one of the following fields will be set, depending on the type.
    """

    control_message: "PayloadTransferFrameControlMessage" = betterproto.message_field(4)


@dataclass(eq=False, repr=False)
class PayloadTransferFramePayloadHeader(betterproto.Message):
    id: int = betterproto.int64_field(1)
    type: "PayloadTransferFramePayloadHeaderPayloadType" = betterproto.enum_field(2)
    total_size: int = betterproto.int64_field(3)
    is_sensitive: bool = betterproto.bool_field(4)
    file_name: str = betterproto.string_field(5)
    parent_folder: str = betterproto.string_field(6)


@dataclass(eq=False, repr=False)
class PayloadTransferFramePayloadChunk(betterproto.Message):
    """Accompanies DATA packets."""

    flags: Optional[int] = betterproto.int32_field(1, optional=True)
    offset: Optional[int] = betterproto.int64_field(2, optional=True)
    body: bytes = betterproto.bytes_field(3)


@dataclass(eq=False, repr=False)
class PayloadTransferFrameControlMessage(betterproto.Message):
    """Accompanies CONTROL packets."""

    event: "PayloadTransferFrameControlMessageEventType" = betterproto.enum_field(1)
    offset: int = betterproto.int64_field(2)


@dataclass(eq=False, repr=False)
class BandwidthUpgradeNegotiationFrame(betterproto.Message):
    event_type: "BandwidthUpgradeNegotiationFrameEventType" = betterproto.enum_field(1)
    upgrade_path_info: "BandwidthUpgradeNegotiationFrameUpgradePathInfo" = (
        betterproto.message_field(2)
    )
    """Exactly one of the following fields will be set."""

    client_introduction: "BandwidthUpgradeNegotiationFrameClientIntroduction" = (
        betterproto.message_field(3)
    )
    client_introduction_ack: "BandwidthUpgradeNegotiationFrameClientIntroductionAck" = (
        betterproto.message_field(4)
    )


@dataclass(eq=False, repr=False)
class BandwidthUpgradeNegotiationFrameUpgradePathInfo(betterproto.Message):
    """Accompanies UPGRADE_PATH_AVAILABLE and UPGRADE_FAILURE events."""

    medium: "BandwidthUpgradeNegotiationFrameUpgradePathInfoMedium" = (
        betterproto.enum_field(1)
    )
    wifi_hotspot_credentials: (
        "BandwidthUpgradeNegotiationFrameUpgradePathInfoWifiHotspotCredentials"
    ) = betterproto.message_field(2)
    """Exactly one of the following fields will be set."""

    wifi_lan_socket: "BandwidthUpgradeNegotiationFrameUpgradePathInfoWifiLanSocket" = (
        betterproto.message_field(3)
    )
    bluetooth_credentials: (
        "BandwidthUpgradeNegotiationFrameUpgradePathInfoBluetoothCredentials"
    ) = betterproto.message_field(4)
    wifi_aware_credentials: (
        "BandwidthUpgradeNegotiationFrameUpgradePathInfoWifiAwareCredentials"
    ) = betterproto.message_field(5)
    wifi_direct_credentials: (
        "BandwidthUpgradeNegotiationFrameUpgradePathInfoWifiDirectCredentials"
    ) = betterproto.message_field(6)
    web_rtc_credentials: (
        "BandwidthUpgradeNegotiationFrameUpgradePathInfoWebRtcCredentials"
    ) = betterproto.message_field(8)
    supports_disabling_encryption: bool = betterproto.bool_field(7)
    """Disable Encryption for this upgrade medium to improve throughput."""

    supports_client_introduction_ack: bool = betterproto.bool_field(9)
    """An ack will be sent after the CLIENT_INTRODUCTION frame."""


@dataclass(eq=False, repr=False)
class BandwidthUpgradeNegotiationFrameUpgradePathInfoWifiHotspotCredentials(
    betterproto.Message
):
    """Accompanies Medium.WIFI_HOTSPOT."""

    ssid: str = betterproto.string_field(1)
    password: str = betterproto.string_field(2)
    port: int = betterproto.int32_field(3)
    gateway: str = betterproto.string_field(4)
    frequency: int = betterproto.int32_field(5)
    """This field can be a band or frequency"""


@dataclass(eq=False, repr=False)
class BandwidthUpgradeNegotiationFrameUpgradePathInfoWifiLanSocket(betterproto.Message):
    """Accompanies Medium.WIFI_LAN."""

    ip_address: bytes = betterproto.bytes_field(1)
    wifi_port: int = betterproto.int32_field(2)


@dataclass(eq=False, repr=False)
class BandwidthUpgradeNegotiationFrameUpgradePathInfoBluetoothCredentials(
    betterproto.Message
):
    """Accompanies Medium.BLUETOOTH."""

    service_name: str = betterproto.string_field(1)
    mac_address: str = betterproto.string_field(2)


@dataclass(eq=False, repr=False)
class BandwidthUpgradeNegotiationFrameUpgradePathInfoWifiAwareCredentials(
    betterproto.Message
):
    """Accompanies Medium.WIFI_AWARE."""

    service_id: str = betterproto.string_field(1)
    service_info: bytes = betterproto.bytes_field(2)
    password: str = betterproto.string_field(3)


@dataclass(eq=False, repr=False)
class BandwidthUpgradeNegotiationFrameUpgradePathInfoWifiDirectCredentials(
    betterproto.Message
):
    """Accompanies Medium.WIFI_DIRECT."""

    ssid: str = betterproto.string_field(1)
    password: str = betterproto.string_field(2)
    port: int = betterproto.int32_field(3)
    frequency: int = betterproto.int32_field(4)
    gateway: str = betterproto.string_field(5)


@dataclass(eq=False, repr=False)
class BandwidthUpgradeNegotiationFrameUpgradePathInfoWebRtcCredentials(
    betterproto.Message
):
    """Accompanies Medium.WEB_RTC"""

    peer_id: str = betterproto.string_field(1)
    location_hint: "LocationHint" = betterproto.message_field(2)


@dataclass(eq=False, repr=False)
class BandwidthUpgradeNegotiationFrameClientIntroduction(betterproto.Message):
    """Accompanies CLIENT_INTRODUCTION events."""

    endpoint_id: str = betterproto.string_field(1)
    supports_disabling_encryption: bool = betterproto.bool_field(2)


@dataclass(eq=False, repr=False)
class BandwidthUpgradeNegotiationFrameClientIntroductionAck(betterproto.Message):
    """Accompanies CLIENT_INTRODUCTION_ACK events."""

    pass


@dataclass(eq=False, repr=False)
class KeepAliveFrame(betterproto.Message):
    ack: bool = betterproto.bool_field(1)
    """And ack will be sent after receiving KEEP_ALIVE frame."""


@dataclass(eq=False, repr=False)
class DisconnectionFrame(betterproto.Message):
    """
    Informs the remote side to immediately severe the socket connection.
     Used in bandwidth upgrades to get around a race condition, but may be used
     in other situations to trigger a faster disconnection event than waiting for
     socket closed on the remote side.
    """

    request_safe_to_disconnect: bool = betterproto.bool_field(1)
    """Apply safe-to-disconnect protocol if true."""

    ack_safe_to_disconnect: bool = betterproto.bool_field(2)
    """
    Ack of receiving Disconnection frame will be sent to the sender
     frame.
    """


@dataclass(eq=False, repr=False)
class PairedKeyEncryptionFrame(betterproto.Message):
    """
    A paired key encryption packet sent between devices, contains signed data.
    """

    signed_data: bytes = betterproto.bytes_field(1)
    """
    The encrypted data (raw authentication token for the established
     connection) in byte array format.
    """


@dataclass(eq=False, repr=False)
class MediumMetadata(betterproto.Message):
    supports_5_ghz: bool = betterproto.bool_field(1)
    """True if local device supports 5GHz."""

    bssid: str = betterproto.string_field(2)
    """
    WiFi LAN BSSID, in the form of a six-byte MAC address: XX:XX:XX:XX:XX:XX
    """

    ip_address: bytes = betterproto.bytes_field(3)
    """
    IP address, in network byte order: the highest order byte of the address is
     in byte[0].
    """

    supports_6_ghz: bool = betterproto.bool_field(4)
    """True if local device supports 6GHz."""

    mobile_radio: bool = betterproto.bool_field(5)
    """True if local device has mobile radio."""

    ap_frequency: int = betterproto.int32_field(6)
    """
    The frequency of the WiFi LAN AP(in MHz). Or -1 is not associated with an
     AP over WiFi, -2 represents the active network uses an Ethernet transport.
    """

    available_channels: "AvailableChannels" = betterproto.message_field(7)
    """Available channels on the local device."""

    wifi_direct_cli_usable_channels: "WifiDirectCliUsableChannels" = (
        betterproto.message_field(8)
    )
    """Usable WiFi Direct client channels on the local device."""

    wifi_lan_usable_channels: "WifiLanUsableChannels" = betterproto.message_field(9)
    """Usable WiFi LAN channels on the local device."""

    wifi_aware_usable_channels: "WifiAwareUsableChannels" = betterproto.message_field(
        10
    )
    """Usable WiFi Aware channels on the local device."""

    wifi_hotspot_sta_usable_channels: "WifiHotspotStaUsableChannels" = (
        betterproto.message_field(11)
    )
    """Usable WiFi Hotspot STA channels on the local device."""


@dataclass(eq=False, repr=False)
class AvailableChannels(betterproto.Message):
    """Available channels on the local device."""

    channels: List[int] = betterproto.int32_field(1)


@dataclass(eq=False, repr=False)
class WifiDirectCliUsableChannels(betterproto.Message):
    """Usable WiFi Direct client channels on the local device."""

    channels: List[int] = betterproto.int32_field(1)


@dataclass(eq=False, repr=False)
class WifiLanUsableChannels(betterproto.Message):
    """Usable WiFi LAN channels on the local device."""

    channels: List[int] = betterproto.int32_field(1)


@dataclass(eq=False, repr=False)
class WifiAwareUsableChannels(betterproto.Message):
    """Usable WiFi Aware channels on the local device."""

    channels: List[int] = betterproto.int32_field(1)


@dataclass(eq=False, repr=False)
class WifiHotspotStaUsableChannels(betterproto.Message):
    """Usable WiFi Hotspot STA channels on the local device."""

    channels: List[int] = betterproto.int32_field(1)


@dataclass(eq=False, repr=False)
class LocationHint(betterproto.Message):
    """LocationHint is used to specify a location as well as format."""

    location: str = betterproto.string_field(1)
    """
    Location is the location, provided in the format specified by format.
    """

    format: "LocationStandardFormat" = betterproto.enum_field(2)
    """the format of location."""


@dataclass(eq=False, repr=False)
class LocationStandard(betterproto.Message):
    pass


@dataclass(eq=False, repr=False)
class OsInfo(betterproto.Message):
    """Device capability for OS information."""

    type: "OsInfoOsType" = betterproto.enum_field(1)
