# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ukey.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nukey.proto\x12\tsecuregcm\"\xb8\x01\n\x0cUkey2Message\x12\x32\n\x0cmessage_type\x18\x01 \x01(\x0e\x32\x1c.securegcm.Ukey2Message.Type\x12\x14\n\x0cmessage_data\x18\x02 \x01(\x0c\"^\n\x04Type\x12\x16\n\x12UNKNOWN_DO_NOT_USE\x10\x00\x12\t\n\x05\x41LERT\x10\x01\x12\x0f\n\x0b\x43LIENT_INIT\x10\x02\x12\x0f\n\x0bSERVER_INIT\x10\x03\x12\x11\n\rCLIENT_FINISH\x10\x04\"\xaf\x02\n\nUkey2Alert\x12-\n\x04type\x18\x01 \x01(\x0e\x32\x1f.securegcm.Ukey2Alert.AlertType\x12\x15\n\rerror_message\x18\x02 \x01(\t\"\xda\x01\n\tAlertType\x12\x0f\n\x0b\x42\x41\x44_MESSAGE\x10\x01\x12\x14\n\x10\x42\x41\x44_MESSAGE_TYPE\x10\x02\x12\x15\n\x11INCORRECT_MESSAGE\x10\x03\x12\x14\n\x10\x42\x41\x44_MESSAGE_DATA\x10\x04\x12\x0f\n\x0b\x42\x41\x44_VERSION\x10\x64\x12\x0e\n\nBAD_RANDOM\x10\x65\x12\x18\n\x14\x42\x41\x44_HANDSHAKE_CIPHER\x10\x66\x12\x15\n\x11\x42\x41\x44_NEXT_PROTOCOL\x10g\x12\x12\n\x0e\x42\x41\x44_PUBLIC_KEY\x10h\x12\x13\n\x0eINTERNAL_ERROR\x10\xc8\x01\"\xf5\x01\n\x0fUkey2ClientInit\x12\x0f\n\x07version\x18\x01 \x01(\x05\x12\x0e\n\x06random\x18\x02 \x01(\x0c\x12G\n\x12\x63ipher_commitments\x18\x03 \x03(\x0b\x32+.securegcm.Ukey2ClientInit.CipherCommitment\x12\x15\n\rnext_protocol\x18\x04 \x01(\t\x1a\x61\n\x10\x43ipherCommitment\x12\x39\n\x10handshake_cipher\x18\x01 \x01(\x0e\x32\x1f.securegcm.Ukey2HandshakeCipher\x12\x12\n\ncommitment\x18\x02 \x01(\x0c\"\x81\x01\n\x0fUkey2ServerInit\x12\x0f\n\x07version\x18\x01 \x01(\x05\x12\x0e\n\x06random\x18\x02 \x01(\x0c\x12\x39\n\x10handshake_cipher\x18\x03 \x01(\x0e\x32\x1f.securegcm.Ukey2HandshakeCipher\x12\x12\n\npublic_key\x18\x04 \x01(\x0c\")\n\x13Ukey2ClientFinished\x12\x12\n\npublic_key\x18\x01 \x01(\x0c*M\n\x14Ukey2HandshakeCipher\x12\x0c\n\x08RESERVED\x10\x00\x12\x0f\n\x0bP256_SHA512\x10\x64\x12\x16\n\x11\x43URVE25519_SHA512\x10\xc8\x01\x42:\n+com.google.security.cryptauth.lib.securegcmB\tUkeyProtoH\x03')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ukey_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n+com.google.security.cryptauth.lib.securegcmB\tUkeyProtoH\003'
  _UKEY2HANDSHAKECIPHER._serialized_start=941
  _UKEY2HANDSHAKECIPHER._serialized_end=1018
  _UKEY2MESSAGE._serialized_start=26
  _UKEY2MESSAGE._serialized_end=210
  _UKEY2MESSAGE_TYPE._serialized_start=116
  _UKEY2MESSAGE_TYPE._serialized_end=210
  _UKEY2ALERT._serialized_start=213
  _UKEY2ALERT._serialized_end=516
  _UKEY2ALERT_ALERTTYPE._serialized_start=298
  _UKEY2ALERT_ALERTTYPE._serialized_end=516
  _UKEY2CLIENTINIT._serialized_start=519
  _UKEY2CLIENTINIT._serialized_end=764
  _UKEY2CLIENTINIT_CIPHERCOMMITMENT._serialized_start=667
  _UKEY2CLIENTINIT_CIPHERCOMMITMENT._serialized_end=764
  _UKEY2SERVERINIT._serialized_start=767
  _UKEY2SERVERINIT._serialized_end=896
  _UKEY2CLIENTFINISHED._serialized_start=898
  _UKEY2CLIENTFINISHED._serialized_end=939
# @@protoc_insertion_point(module_scope)
